### ISSUE TITLE
Considerations for moving this beyond an experiment?

### ISSUE THREAD

**Issue by tmlayton** [ssorallen/turbo-react#19]
@ssorallen continuation from rails/turbolinks#491

**Comment by qq99** [comment]
I think the following should happen:

- [ ] Turbolinks PR to expose `Turbolinks.replaceNode(...)` as the public API, so a monkey patch isn't needed
- [ ] https://github.com/ssorallen/turbo-react/blob/master/src/reactize.js#L24-L30 should be changed to call the original `Turbolinks.replaceNode(...)`

**Comment by ssorallen** [comment]
* TurboReact currently includes Turbolinks, but I don't think it should. This is
  essentialy a Turbolinks plugin, so it should have Turbolinks as one of its
  `peerDependencies` at best.
* Tlinks 3.0 has partial replacement, which might be enough API to fix the need
  for monkeypatching `replaceNode`. It needs some more investigation.

**Comment by ssorallen** [comment]
* TurboReact has to disable the Turboinks page cache because it otherwise
  caches React's version of the DOM with `data-react-id` attributes. Diff'ing
  doesn't work after that because the existence of those attrs makes React
  treat the DOM as a pre-rendered document. Unsure if there are enough hooks
  to circumvent that?

**Comment by qq99** [comment]
>TurboReact currently includes Turbolinks, but I don't think it should

agreed 100% :)  also, it'd be very nice if it were available as a rails engine

**Comment by ssorallen** [comment]
@qq99, I'm familiar with Rails but not with writing Rails engines. I can check that out too.

**Comment by ssorallen** [comment]
> https://github.com/ssorallen/turbo-react/blob/e0048b78d2c915d0517efff1afdf9c6cf7b6ca75/src/reactize.js#L24-L30 should be changed to call the original Turbolinks.replaceNode(...)

I took that suggestion and implemented it in commit https://github.com/ssorallen/turbo-react/commit/2ffd0311ee6c0b1f3fc3be50f8a5914e41fe562f.

**Comment by nateberkopec** [comment]
What would making TurboReact a Rails engine solve? Happy to take a stab at it but I don't understand the benefit.

**Comment by qq99** [comment]
It let's you install it more like:

1.  `gem 'turboreact'` into your Gemfile
2.  `#= require turboreact` in your application.js manifest
3.  It's all working and good-to-go

It seems a bit strange to have to use npm to install something in a RoR project

**Comment by ssorallen** [comment]
:+1: @qq99, if you are familiar with Rails Engines a "turboreact-rails" Gem would be great. I agree using NPM in a Rails project feels awkward.

**Comment by jbhatab** [comment]
So is this suitable for production? The only thing that threw me off was the caching of react ids. Seems like it could break stuff.

**Comment by ssorallen** [comment]
@jbhatab TurboReact currently [disables the Turbolinks cache](https://github.com/ssorallen/turbo-react/blob/master/src/turbo-react.js#L15) because of the problem of caching React IDs.

The library doesn't have automated testing yet, but if it runs into any problems it falls back to letting Turbolinks work like normal. If you are comfortable with [`document.replaceChild` being monkeypatched](https://github.com/ssorallen/turbo-react/issues/20), feel free to try it out.
